corner-radius = 0;

blur: {
  method = "gaussian";
  size = 10;
  strength = 7;
};

inactive-opacity = 0.85; 
active-opacity = 1.0; 

blur-background = true;
blur-background-fixed = true;

fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

backend = "glx";

dithered-present = false;
vsync = true;


detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = true;
detect-transient = true;
use-damage = true;
log-level = "warn";


# WINDDOW RULES
rules = (
	# { match = "name = 'dwm'"; opacity = 1; },
  { match = "class_g = 'Polybar'"; opacity = 1.0; shadow = false; },
	{ match = "focused"; opacity = 1; },
	{ match = "!focused"; opacity = 0.85; },
	{ match = "tooltip"; fade = true; shadow = true; opacity = 0.5; focus = true; full-shadow = false; },
	{ match = "popup_menu"; opacity = 0.7; },
  { match = "dropdown_menu"; opacity = 0.7; }
);
