
corner-radius = 0 
# BLURRING
# methods: none, gaussian, box, kernel (define custom kernel), dual_kawase
blur:
{
  method = "gaussian";
  size = 10;
  strength = 3;
# default deviation is 0.84
# deviation = false;
};

# semi-transparent
blur-background = true

# Use fixed blur strength rather than adjusting according to window opacity.
blur-background-fixed = true



# SHADOWS
shadow = true;
shadow-radius = 6;
shadow-opacity = .25
shadow-offset-x = 0;
shadow-offset-y = 4;

# FADING
fading = true;

fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3


# backends: `xrender`, `glx`, `egl` or `xr_glx_hybrid`
backend = "glx";

dithered-present = false;
vsync = true;


detect-rounded-corners = true;
detect-client-opacity = true;
use-ewmh-active-win = true
detect-transient = true;
use-damage = true;
log-level = "warn";

# WINDDOW RULES
rules = (
	# { match = "name = 'dwm'"; opacity = 1; },
  { match = "class_g = 'Polybar'"; opacity = 0.90; shadow = true; },
	{ match = "focused"; opacity = 1; },
	{ match = "!focused"; opacity = 0.85; },
	{ match = "tooltip"; fade = true; shadow = true; opacity = 0.5; focus = true; full-shadow = false; },
	{ match = "popup_menu"; opacity = 0.7; },
	{ match = "dropdown_menu"; opacity = 0.7; },
  { match = "class_g = 'Polybar'"; opacity = 1.0; },
  )

